import {
  HomeOutlined as HomeOutlinedIcon,
  ArrowForwardIos as ArrowForwardIosIcon,
  ArrowBackIos as ArrowBackIosIcon,
  PeopleOutlined as PeopleOutlinedIcon,
  ReceiptOutlined as ReceiptOutlinedIcon,
  BarChartOutlined as BarChartOutlinedIcon,
  MapOutlined as MapOutlinedIcon,
  Groups as GroupsIcon,
  OndemandVideo as OndemandVideoIcon,
  VideoCall as VideoCallIcon,
  Web as WebIcon,
  Quiz as QuizIcon,
  Wysiwyg as WysiwygIcon,
  ManageHistory as ManageHistoryIcon,
  Settings as SettingsIcon,
  ExitToApp as ExitToAppIcon,
} from "@mui/icons-material";

export {
  HomeOutlinedIcon,
  ArrowForwardIosIcon,
  ArrowBackIosIcon,
  PeopleOutlinedIcon,
  ReceiptOutlinedIcon,
  BarChartOutlinedIcon,
  MapOutlinedIcon,
  GroupsIcon,
  OndemandVideoIcon,
  VideoCallIcon,
  WebIcon,
  QuizIcon,
  WysiwygIcon,
  ManageHistoryIcon,
  SettingsIcon,
  ExitToAppIcon,
};
